AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.5
  SuggestExtensions: false

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
